version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.10.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  logstash:
    image: logstash:8.10.4
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
