version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./packages/backend/api/Dockerfile
      args:
        packagejson: './package.json'
        env: './.env.docker'
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000

  emails:
    build:
      context: .
      dockerfile: ./packages/backend/email-service/Dockerfile
      args:
        packagejson: './package.json'
        env: './.env.docker'
    restart: always
    depends_on:
      - rmq

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgres/data

  rmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  elasticsearch:
    image: elasticsearch:8.10.4
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  logstash:
    image: logstash:8.10.4
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  database_data:
